### ISSUE TITLE
BET produces brain mask with different orientations/field of view

### ISSUE THREAD

**Issue by JohannaHeu** [pauldmccarthy/fslpy#14]
Hi 

I am struggling with BET. I try to produce a binary brain mask with bet. As an input image I use a nii file T1 post-contrast MRI. When I run the code it produces a brain extraction and a brain mask as I want to. But if I open the brain mask in fsleyes, the t1 post contrast image and the brain mask have the same coordinates, but fsleyes writes a warning: "Displaying images with different orientations/fields of view!".
Following I can not use the brain mask for eg. normalization as it also gives me an error that the images are not in the same space.

With a different T1 post-contrast image it was already working fine and the mask an image were in the same space. I just do not understand why now with another image it is not working any more.

Maybe you can help me with that problem?

I wrote this code part:

```
mask_brain = fsl.BET()

try:
    mask_brain.inputs.in_file = os.path.join(path, filename3)                      # path of t1km
    mask_brain.inputs.mask = True
    mask_brain.inputs.out_file = os.path.join(path, filename14)                  # path of brain extraction image of t1km
    #mask_brain.inputs.mask_file = os.path.join(path, filename13)
    mask_brain.cmdline 
    'bet os.path.join(path, filename7) os.path.join(path, filename14) -m'     # path of brain extraction and brain mask image of t1km_reg
    res = mask_brain.run()                                                                                                                          
except OSError:
    print ("Creating T1km Brain Mask failed") 
else: 
    print ("Creating T1km Brain Mask successfull")
```

Greetings Johanna

**Comment by JohannaHeu** [comment]
Update: I found maybe the root to the problem. I adjusted the brain mask manually with ITK-SNAP and afterwards the brain mask is not in the same orientation/field of view.

Is there any trick I can do so that this does not happen?

**Comment by pauldmccarthy** [comment]
Hi Johanna, did you change the FOV of the mask image using ITK-SNAP? This is not a good idea, as many tools (FSL and otherwise), when given a set of images, expect all of those images to have the same FOV and voxel grid. So if you changed the FOV of the mask, you would also need to change the FOV of your original T1 image to match.

Or, better, adjust the FOV of your T1 image before running BET.

If you didn't adjust the FOV of your mask image, and were just using ITK-SNAP to tweak the brain mask (adding/removing voxels), then it could be that ITK-SNAP has adjusted/overridden the orientation information in the mask image header. You should be able to fix this by using the `fslcpgeom` command to copy the original orientation information from your T1 image over to your mask image, e.g.: `fslcpgeom <T1_image> <mask_image>`

**Comment by JohannaHeu** [comment]
Thank you very much for your quick reply! 
I used the command fslcpgeom on the segmentation done with ITK-SNAP and now they are in the correct orientation again. 

I hope this is the correct way to adjust the FOV at the end after the segmentation
